accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings

from .views import ProfessorView, StudentView, AuthenticationViews, StudentAccountViews, \
    TeacherAccountViews, popular_quiz

app_name = 'accounts'

urlpatterns = [
    path('login/', AuthenticationViews.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('student_auth/', StudentView.as_view(), name='student_auth'),
    path('professor_auth/', ProfessorView.as_view(), name='professor_auth'),

    path('student/<int:student_id>', StudentAccountViews.as_view(), name='student'),
    path('teacher/<int:teacher_id>', TeacherAccountViews.as_view(), name='teacher'),

    path('popular/', popular_quiz, name='popular')
]

bars_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
]

urlpatterns += [
    path('accounts/', include('accounts.urls', namespace='account')),
    path('', include('user_tests.urls', namespace='user_tests'))
]

user_tests/urls.py
from django.urls import path

from .views import MainViews, QuizViews, EditQuizViews, ResultQuiz

app_name = 'user_tests'

urlpatterns = [
    path('', MainViews.as_view(), name='main'),
    path('quiz/<int:quiz_id>', QuizViews.as_view(), name='quiz'),
    path('processing/', QuizViews.as_view(), name='processing'),

    path('edit_quiz/<int:quiz_id>', EditQuizViews.as_view(), name='edit_quiz'),
    path('create_quiz/', EditQuizViews.as_view(), name='create_quiz'),

    path('result_detail/<str:unique_pk>', ResultQuiz.as_view(), name='result_detail'),
]

templates/include/header.html
<header class="header">
    <div class="wrapper">
        <div class="header__content">
            <a href="{% url 'user_tests:main' %}" class="header__home">
                <div class="material-icons header__home--icon">
                    home
                </div>

                <div class="header__home--text">
                    На главную
                </div>
            </a>
            <a href="{% url 'accounts:popular' %}" class="header__home">
                <div class="header__home--text">
                    Список популярных курсов
                </div>
            </a>

            {% if user.is_authenticated %}
            <div class="header__user">
                <div class="header__user--info">
                    <div class="header__user--name">
                        <span><a href="{% url 'accounts:student' request.user.id %}">{{ user.first_name }} {{ user.last_name }}</a></span>
                    </div>
                </div>

                <a href="{% url 'accounts:logout' %}" class="header__user--logout">
                    <span class="material-icons logout-icon">
                        logout
                    </span>
                </a>

            </div>
            {% else %}
                <div class="header__login">
                    <a href="{% url 'accounts:login' %}">
                        Войти
                    </a>

                    <a href="{% url 'accounts:student_auth' %}">
                        Регистрация
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</header>

templates/include/pagination.html
{% if page_obj.paginator.num_pages > 1 %}
    <nav class="pagination">
        <ul class="pagination__list">
            {% if page_obj.has_previous %}
                <li class="pagination__item">
                <a href="?page={{ page_obj.previous_page_number }}" class="pagination__link" title="Предыдущая страница">
                    <span class="material-icons">arrow_back</span>
                </a>
            </li>
            {% endif %}

            {% for pg in page_obj.paginator.page_range %}
                {% if page_obj.number == pg %}
                    <li class="pagination__item active">
                        <a class="pagination__link">{{ pg }}</a>
                    </li>
                {% elif pg > 1 %}
                    <li class="pagination__item">
                        <a class="pagination__link" href="{% if url_params %}{{ url_params }}&{% else %}?{% endif %}page={{ pg }}" title="Страница {{ pg }}"{% if classes %} class="page-link {{ classes }}"{% endif %}>{{ pg }}</a>
                    </li>
                {% else %}
                    <li class="pagination__item">
                        <a class="pagination__link" href="{{ request.path }}{{ url_params }}" title="Первая страница"{% if classes %} class=" page-link {{ classes }}"{% endif %}>{{ pg }}</a>
                    </li>
                {% endif %}
            {% endfor %}


            {% if page_obj.has_next %}
                <li class="pagination__item">
                    <a href="?page={{ page_obj.next_page_number }}" class="pagination__link" title="Следующая страница">
                        <span class="material-icons">
                        arrow_forward
                        </span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}