accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings

from .views import ProfessorView, StudentView, AuthenticationViews, StudentAccountViews, \
    TeacherAccountViews, popular_quiz

app_name = 'accounts'

urlpatterns = [
    path('login/', AuthenticationViews.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('student_auth/', StudentView.as_view(), name='student_auth'),
    path('professor_auth/', ProfessorView.as_view(), name='professor_auth'),

    path('student/<int:student_id>', StudentAccountViews.as_view(), name='student'),
    path('teacher/<int:teacher_id>', TeacherAccountViews.as_view(), name='teacher'),

    path('popular/', popular_quiz, name='popular')
]

bars_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
]

urlpatterns += [
    path('accounts/', include('accounts.urls', namespace='account')),
    path('', include('user_tests.urls', namespace='user_tests'))
]

user_tests/urls.py
from django.urls import path

from .views import MainViews, QuizViews, EditQuizViews, ResultQuiz

app_name = 'user_tests'

urlpatterns = [
    path('', MainViews.as_view(), name='main'),
    path('quiz/<int:quiz_id>', QuizViews.as_view(), name='quiz'),
    path('processing/', QuizViews.as_view(), name='processing'),

    path('edit_quiz/<int:quiz_id>', EditQuizViews.as_view(), name='edit_quiz'),
    path('create_quiz/', EditQuizViews.as_view(), name='create_quiz'),

    path('result_detail/<str:unique_pk>', ResultQuiz.as_view(), name='result_detail'),
]

user_tests/models.py
import textwrap

from django.db import models
from django.contrib.auth.models import User

from common.models import AbsDescription, AbsActive, AbsCreated, AbsSort


class Quiz(AbsDescription, AbsActive, AbsCreated, AbsSort):
    """
    Тест
    """

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'
        ordering = ['id']

    def __str__(self):
        return textwrap.shorten(self.title, width=80, placeholder=f'{self.title[:10]}...')


class Question(AbsDescription, AbsActive, AbsCreated, AbsSort):
    """
    Вопрос
    """

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name='Тест', related_name='questions')

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return textwrap.shorten(self.title, width=80, placeholder=f'{self.title[:10]}...')


class Variant(AbsActive, AbsCreated, AbsSort):
    """
    Вариант ответа
    """

    questions = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос', related_name='variants')
    correct = models.BooleanField('Правильный ответ', default=False)
    title = models.CharField('Название', max_length=250)

    class Meta:
        verbose_name = 'Вариант'
        verbose_name_plural = 'Варианты'

    def __str__(self):
        return textwrap.shorten(self.title, width=80, placeholder=f'{self.title[:10]}...')


class UniqueValue(AbsCreated):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='unique_user')
    unique_value = models.CharField('Уникальный идентификатор теста', max_length=100)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name='Тест', related_name='unique_quiz', null=True, blank=True)

    class Meta:
        verbose_name = 'Уникальное значение'
        verbose_name_plural = 'Уникальные значения'

    def __str__(self):
        return self.unique_value


class Answer(AbsCreated):
    unique = models.ForeignKey(UniqueValue, on_delete=models.CASCADE, related_name='result_unique', verbose_name='Идентификатор теста')
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Вопрос', related_name='result_questions')
    variant = models.ForeignKey(Variant, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='', related_name='result_variant')
    correct_answer = models.BooleanField('Правильный ответ', default=False)

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def __str__(self):
        return f'Answer to the question-{self.question}'

user_tests/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import Quiz, Question, Variant


class QuizEditForm(ModelForm):
    """
    Тест. Поля:
    'title' - Название
    'description' - Описание
    'is_active' - Активность
    """
    class Meta:
        model = Quiz
        fields = ['title', 'description', 'is_active']


class QuestionsForm(ModelForm):
    """
    Вопрос. Поля:
    'title' - Название
    'description' - Описание
    'is_active' - Активность
    'sort' - Сортировка
    """
    class Meta:
        model = Question
        fields = ['title', 'description', 'is_active', 'sort']


# FormSet для теста и вопросов
QuestionsFormSet = inlineformset_factory(Quiz, Question, can_delete=True, form=QuestionsForm)


class VariantsForm(ModelForm):
    """
    Варианты ответа. Поля:
    'title' - Название
    'description' - Описание
    'is_active' - Активность
    'sort' - Сортировка
    'questions' - Варианты ответа
    'correct' - Правильный ответ
    """
    class Meta:
        model = Variant
        fields = ['title', 'is_active', 'sort', 'questions', 'correct']


# FormSet для вопроса и вариантов ответа
VariantsFormSet = inlineformset_factory(Question, Variant, can_delete=True, form=VariantsForm)

user_tests/views.py
import secrets
import string

from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.paginator import Paginator

from .models import Quiz, Question, Variant, UniqueValue, Answer
from .forms import QuizEditForm, QuestionsFormSet, VariantsFormSet


class MainViews(LoginRequiredMixin, TemplateView):
    """
    Представление главной страницы.
    Содержит в себе список имеющихся статей с пагинацией
    """
    template_name = 'user_tests/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quizzes = Quiz.objects.filter(is_active=True)
        paginator = Paginator(quizzes, 2)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class QuizViews(LoginRequiredMixin, TemplateView):
    """
    Тестирование.
    Обрабатывает входные данные и записывает ответы в базу
    с уникальным идентификатором тестирования
    """
    template_name = 'user_tests/quiz.html'
    queryset_variants = Variant.objects.filter(is_active=True)

    def __init__(self):
        super().__init__()
        self.result_dict = []
        self.unique_pk = ''

    def get(self, request, *args, **kwargs):
        self.unique_pk = ''.join(secrets.choice(string.ascii_letters + string.digits) for _ in range(50))
        request.session['key_test'] = self.unique_pk

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        answer_list = request.POST.getlist('answer')
        quiz = request.POST.get('quiz_id')
        unique_pk = request.session.get('key_test')

        answers = Variant.objects.filter(id__in=answer_list).values('id', 'correct', 'questions')

        unique_value = UniqueValue.objects.get_or_create(
            unique_value=unique_pk,
            defaults={
                'user_id': request.user.id,
                'quiz_id': int(quiz)
            }
        )

        data = []
        for answer_item in answers:
            data.append(Answer(
                unique_id=unique_value[0].id,
                question_id=answer_item.get('questions'),
                variant_id=answer_item.get('id'),
                correct_answer=answer_item.get('correct')
            ))

        Answer.objects.bulk_create(data)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        questions = Question.objects.filter(quiz_id=kwargs.get('quiz_id'))
        context['questions'] = questions
        context['question_item'] = questions.first()
        context['unique_pk'] = self.unique_pk

        return context


class EditQuizViews(LoginRequiredMixin, TemplateView):
    """
    Редактирование тестов
    Выводит список готовых тестов с заполненной информаций
    """
    template_name = 'user_tests/edit_quiz.html'

    def __init__(self):
        super().__init__()
        self.form = None
        self.quiz = None

    def get(self, request, *args, **kwargs):
        self.quiz = Quiz.objects.filter(id=kwargs.get('quiz_id')).prefetch_related('questions')

        self.form = QuizEditForm(instance=self.quiz.first())

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        quiz_pk = kwargs.get('quiz_id')
        self.quiz = Quiz.objects.filter(id=quiz_pk).first()
        self.form = QuizEditForm(request.POST, instance=self.quiz)

        if self.form.is_valid():
            self.form = self.form.save(commit=False)

            question_form = QuestionsFormSet(request.POST, instance=self.form)

            if question_form.is_valid():
                question_form.save(commit=False)

                variants = VariantsFormSet(request.POST, instance=question_form)
                if variants.is_valid():
                    variants.save()

                question_form.save()
            self.form.save()
            messages.info(request, 'Success')

            if quiz_pk:
                return redirect(reverse('user_tests:edit_quiz', kwargs={'quiz_id': quiz_pk}))
            else:
                return redirect(reverse('user_tests:create_quiz'))
        else:
            messages.error(request, 'Ошибка в валидации формы')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        context['variants'] = VariantsFormSet()
        context['question_form'] = QuestionsFormSet()
        context['quiz_pk'] = kwargs.get('quiz_id')

        return context


class ResultQuiz(LoginRequiredMixin, TemplateView):
    """
    Обработка результатов тестирования
    """
    template_name = 'user_tests/test_final.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'unique_pk' in kwargs:
            result_unique = UniqueValue.objects.filter(unique_value=kwargs.get('unique_pk')).prefetch_related('result_unique').first()
            context['result_unique'] = result_unique

            context['result_quiz'] = counting_responses(result_unique)

        return context


def counting_responses(results) -> dict:
    """
    Подсчет ответов, процентного соотношения и оценки
    :param results: queryset отвеченных вопросов
    :return result_answer: Словарь с оценочными параметрами
    """
    user_selection = {}
    for answer in results.result_unique.all():
        question = answer.question_id
        if question not in user_selection:
            user_selection[question] = []
        user_selection[question].append(answer.correct_answer)

    result_answer = {
        'quantity': 0,
        'correct': 0,
        'wrong': 0,
        'percent': 0,
        'assessment': 0
    }
    for question, answer in user_selection.items():
        result_answer['quantity'] += 1
        answer_set = set(answer)
        if len(answer_set) == 1 and True in answer_set:
            result_answer['correct'] += 1
        else:
            result_answer['wrong'] += 1

    try:
        result_answer['percent'] = round((result_answer['correct'] / result_answer['quantity']) * 100, 2)
    except ZeroDivisionError:
        pass

    if result_answer['percent'] <= 50:
        result_answer['assessment'] = 2
    elif 75 >= result_answer['percent'] > 50:
        result_answer['assessment'] = 3
    elif 90 >= result_answer['percent'] > 75:
        result_answer['assessment'] = 4
    else:
        result_answer['assessment'] = 5

    return result_answer

user_tests/templates/user_tests/edit_quiz.html
{% extends 'layouts/base.html' %}


{% block content %}
    <h1>Форма для редактирования</h1>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <h1>Добавить новый вопрос:</h1>
        {{ question_form.management_form }}
        {% for item in question_form.forms %}
            <div class="question">
                <h2>Вопрос:</h2>
                {{ item.as_p }}
                {{ variants.management_form }}

                    {% for variant in variants %}
                        <div class="variant">
                            <h2>Вариант ответа:</h2>
                            {{ variant.as_p }}
                        </div>
                    {% endfor %}

                <p>------------------------------------------------------------------------</p>
            </div>
        {% endfor %}

        <button type="submit">{% if quiz_pk %}Редактировать{% else %}Создать{% endif %}</button>
    </form>

{% endblock %}

user_tests/templates/user_tests/main.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="content">
            <main>
                <div class="wrapper">
                    <section class="tests__list">
                        <div class="header-block">
                            <h2>
                                Список тестовых заданий
                            </h2>
                        </div>

                        <div class="tests__list--content">
                            {% if page_obj %}
                                {% for quiz in page_obj %}
                                    <div class="tests__card">

                                        <h4 class="tests__card--title">{{ quiz.title }}</h4>
                                        <div class="tests__card--desc desc">
                                            <p class="desc__text">
                                                {{ quiz.description }}
                                            </p>

                                            <div class="desc__bottom">
                                                <a href="{% url 'user_tests:edit_quiz' quiz.id %}"
                                                   class="desc__link"><span class="text">Редактировать</span></a>

                                                <a href="{% url 'user_tests:quiz' quiz.id %}" class="desc__link"><span
                                                        class="text">Перейти к тесту</span><span
                                                        class="material-icons">arrow_right_alt</span></a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                    </section>
                    {% include 'include/pagination.html' %}
                </div>
            </main>
        </div>
    </div>
{% endblock %}

user_tests/templates/user_tests/quiz.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="main">
    <div class="wrapper">
        <section class="test-detail">

            <div class="header-block">
                <h2>{{ question_item.quiz.title }}</h2>
            </div>

            <div class="test-detail__content">
                <div class="test-detail__content--desc desc">
                    <h4 class="desc__title">
                        Описание теста
                    </h4>
                    <div class="desc__content">
                        <p>{{ question_item.quiz.description }}</p>
                    </div>
                    <div class="desc__controls">
                        <a href="/" class="btn btn--primary start">Начать тестирование</a>
                    </div>
                </div>
                <div class="test-detail__content--info info">
                    <h4 class="info__title">Информация</h4>

                    <div class="info__content">
                        <div class="info__item">
                            <span class="point">
                                Общее количество вопросов:
                            </span>
                            <span class="value">
                                {{ questions.count }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </section>

        <section class="test__quiz" id="testBody">

            <div class="test__quiz--list quiz">
            {% for question in questions %}
                <div class="quiz__item {% if forloop.first %}active{% endif %}">

                    <h5 class="quiz__item--title question">
                        {{ question.title }}
                    </h5>
                    <div class="desc__content">
                      <p>
                          {{ question.description }}
                      </p>
                    </div>

                    <form class="quiz__item--content">
                        {% csrf_token %}
                        <input type="hidden" name="quiz_id" value="{{ question.quiz.id }}">
                        {% for variant in question.variants.all %}
                            <label class="field field-check">
                                <input type="checkbox" name="answer" class="field-check__input" value="{{ variant.id }}">
                                <span class="field-check__name">{{ variant.title }}</span>
                            </label>
                        {% endfor %}

                        <button class="btn btn--primary quiz__item--btn" disabled>Ответить</button>
                    </form>
                </div>
            {% endfor %}

            </div>

            <aside class="test__quiz--aside aside">
                <div class="aside__block">
                    <span>Вопрос</span>
                    <!-- счетчик обновляется на каждой итерации сабмита формы кроме последней -->
                    <span id="count">1</span>
                    <span>из</span>
                    <span>{{ questions.count }}</span>
                </div>

                <a href="{% if unique_pk %}{% url 'user_tests:result_detail' unique_pk %}
                        {% else %}{% url 'user_tests:result' %}{% endif %}" class="btn btn--primary aside__btn" id="final">
                    Узнать результаты
                </a>

            </aside>

        </section>
    </div>
</div>

<script>
    const quizInit = function () {
        let questions = document.querySelectorAll('.quiz__item');
        let questionCount = 1;
        let questionCountBlock = document.querySelector('#count');

        let url = '/processing/';
        console.log(questions);

        questions.forEach((item, i) => {
            item.id = "question_" + (i + 1);

            let form = item.querySelector('form');
            let btn = form.querySelector('.btn');

            let checkboxes = form.querySelectorAll('input[type="checkbox"]')
            console.log(checkboxes);
            checkboxes.forEach(checkbox => checkbox.addEventListener('change', (e) => {
                let prer = Array.from(checkboxes).filter(checkbox => checkbox.checked === true)
                console.log(prer);
                prer.length > 0 ? btn.disabled = false : btn.disabled = true
                prer.length === checkboxes.length ? btn.disabled = true : btn.disabled = false
                prer.length === checkboxes.length && checkboxes.length !== 1 ? btn.disabled = true : btn.disabled = false
            }));

            form.addEventListener('submit', (e) => {
                e.preventDefault();
                let formData = new FormData(form);
                fetch(url, {
                    method: 'POST',
                    body: formData
                }).then((data) => {
                    form.reset();
                    console.log('response ' + data);
                }).finally(() => {
                    item.classList.remove('active');
                    // если вопрос был не последний
                    if (i + 1 < questions.length) {
                        console.log('not last ' + (i + 1) + ' | ' + questions.length);
                        questionCount += 1;
                        questionCountBlock.textContent = questionCount;
                        setTimeout(() => {
                            item.remove();
                            questions[i + 1].classList.add('active')
                        }, 500);

                    } else {
                        // если последний
                        console.log('last');
                        document.getElementById('final').classList.add('active');
                    }
                })
            })
        });
    }

    const quizStart = function () {
        document.querySelector('.start').addEventListener("click", (e) => {
            e.preventDefault();
            document.getElementById('testBody').classList.add('active');
        });
    }

    document.addEventListener('DOMContentLoaded', () => {
        quizInit();
        quizStart();
    });
</script>

{% endblock %}

user_tests/templates/user_tests/test_final.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="main">
        <div class="wrapper">
            <section class="test-detail">

                <div class="header-block">
                    <h2>{{ result_unique.quiz.title }}</h2>
                </div>

                <div class="test-detail__content">
                    <div class="test-detail__content--desc desc">
                        <h4 class="desc__title">
                            Описание теста
                        </h4>
                        <div class="desc__content">
                            <p>{{ result_unique.quiz.description }}</p>
                        </div>
                        <div class="desc__controls">
                            <a href="{% if result_unique.quiz.id %}{% url 'user_tests:quiz' result_unique.quiz.id %}{% endif %}" class="btn btn--primary">Пройти тестирование заного</a>
                        </div>
                    </div>
                    <div class="test-detail__content--info info">
                        <h4 class="info__title">Итоги тестирования</h4>

                        <div class="info__content">
                            <div class="info__item">
                        <span class="point">
                          Общее количество вопросов:
                        </span>
                                <span class="value">
                          {{ result_quiz.quantity }}
                        </span>
                            </div>

                            <div class="info__item right">
                        <span class="point ">
                          Количество правильных ответов:
                        </span>
                                <span class="value">
                          {{ result_quiz.correct }}
                        </span>
                                <span class="material-icons">
                          check_circle
                        </span>
                            </div>

                            <div class="info__item wrong">
                        <span class="point ">
                          Количество неправильных ответов:
                        </span>
                                <span class="value">
                          {{ result_quiz.wrong }}
                        </span>
                                <span class="material-icons">
                          cancel
                        </span>
                            </div>

                            <div class="info__item">
                        <span class="point ">
                          Процент правильных овтетов:
                        </span>
                                <span class="value">
                          {{ result_quiz.percent }}%
                        </span>

                            </div>

                            <div class="info__item">
                        <span class="point ">
                          Итоговая оценка:
                        </span>
                                <span class="value">
                          {{ result_quiz.assessment }}
                        </span>

                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}