accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings

from .views import ProfessorView, StudentView, AuthenticationViews, StudentAccountViews, \
    TeacherAccountViews, popular_quiz

app_name = 'accounts'

urlpatterns = [
    path('login/', AuthenticationViews.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('student_auth/', StudentView.as_view(), name='student_auth'),
    path('professor_auth/', ProfessorView.as_view(), name='professor_auth'),

    path('student/<int:student_id>', StudentAccountViews.as_view(), name='student'),
    path('teacher/<int:teacher_id>', TeacherAccountViews.as_view(), name='teacher'),

    path('popular/', popular_quiz, name='popular')
]

bars_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nested_admin/', include('nested_admin.urls')),
]

urlpatterns += [
    path('accounts/', include('accounts.urls', namespace='account')),
    path('', include('user_tests.urls', namespace='user_tests'))
]

user_tests/urls.py
from django.urls import path

from .views import MainViews, QuizViews, EditQuizViews, ResultQuiz

app_name = 'user_tests'

urlpatterns = [
    path('', MainViews.as_view(), name='main'),
    path('quiz/<int:quiz_id>', QuizViews.as_view(), name='quiz'),
    path('processing/', QuizViews.as_view(), name='processing'),

    path('edit_quiz/<int:quiz_id>', EditQuizViews.as_view(), name='edit_quiz'),
    path('create_quiz/', EditQuizViews.as_view(), name='create_quiz'),

    path('result_detail/<str:unique_pk>', ResultQuiz.as_view(), name='result_detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from common.models import AbsActive


class StudyGroup(AbsActive):

    title = models.CharField('Название группы', max_length=250)

    class Meta:
        verbose_name = 'Учебная группа'
        verbose_name_plural = 'Учебные группы'

    def __str__(self):
        return self.title


class Student(User):

    study_group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE, verbose_name='Учебная группа',
                                    related_name='student')

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'

    def __str__(self):
        return self.username


class Professor(User):

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import password_validation

from .models import Student, Professor


password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'field__input', 'placeholder': 'Введите пароль', 'required': True},),
        help_text=password_validation.password_validators_help_text_html())
password2 = forms.CharField(widget=forms.PasswordInput(
    attrs={'class': 'field__input', 'placeholder': 'Подтвердите пароль', 'required': True}))


class AuthenticationUserForm(AuthenticationForm):
    """
    Аутентификация пользователей
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'field__input', 'placeholder': 'Введите ваш логин', 'required': True, 'type': 'text'}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'field__input', 'placeholder': 'Введите ваш пароль', 'required': True}),
    )


class StudentForm(UserCreationForm):
    """
    Форма регистрации новых студентов
    """
    password1 = password1
    password2 = password2

    class Meta:
        model = Student
        fields = ['username',
                  'first_name', 'last_name',
                  'password1', 'password2', 'study_group']
        widgets = {
            'username': forms.TextInput(
                attrs={'class': 'field__input', 'placeholder': 'Введите пользователя', 'required': True}, ),
            'first_name': forms.TextInput(
                attrs={'class': 'field__input', 'placeholder': 'Введите имя', 'required': True}, ),
            'last_name': forms.TextInput(
                attrs={'class': 'field__input', 'placeholder': 'Введите фамилию', 'required': True}, ),
            'study_group': forms.Select(attrs={'class': 'field__input', 'placeholder': 'Выберите группу', 'required': True})
        }


class ProfessorForm(UserCreationForm):
    """
    Форма регистрации преподавателей
    """
    password1 = password1
    password2 = password2

    class Meta:
        model = Professor
        fields = ['username',
                  'first_name', 'last_name',
                  'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'field__input', 'placeholder': 'Введите пользователя', 'required': True},),
            'first_name': forms.TextInput(attrs={'class': 'field__input', 'placeholder': 'Введите имя', 'required': True},),
            'last_name': forms.TextInput(attrs={'class': 'field__input', 'placeholder': 'Введите фамилию', 'required': True},),
        }

accounts/views.py
from datetime import datetime
from datetime import date
from django.utils.timezone import make_aware
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import StudentForm, ProfessorForm, AuthenticationUserForm
from user_tests.models import UniqueValue, Quiz


class AuthenticationViews(LoginView):
    """
    Аутентификация пользователя
    """
    form_class = AuthenticationUserForm
    redirect_authenticated_user = True


class ProfessorView(TemplateView):
    """
    Представления для регистрации преподавателя
    """
    template_name = 'accounts/auth_teacher.html'

    def __init__(self):
        super().__init__()
        self.forms = None

    def get(self, request, *args, **kwargs):
        self.forms = ProfessorForm()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.forms = ProfessorForm(request.POST)
        if self.forms.is_valid():
            self.forms.save(commit=False)
            self.forms.save()
            return redirect(reverse('user_tests:main'))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = self.forms
        return context


class StudentView(TemplateView):
    """
    Представление для регистрации студента
    """
    template_name = 'accounts/auth_student.html'

    def __init__(self):
        super().__init__()
        self.student_form = None

    def get(self, request, *args, **kwargs):
        self.student_form = StudentForm()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.student_form = StudentForm(request.POST)
        if self.student_form.is_valid():
            self.student_form.save(commit=False)
            self.student_form.save()
            return redirect(reverse('user_tests:main'))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['student_form'] = self.student_form
        return context


class StudentAccountViews(LoginRequiredMixin, TemplateView):
    """
    Личный кабинет студента.
    Выводятся все пройденные тесты данным пользователем
    """
    template_name = 'accounts/student.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_quiz = UniqueValue.objects.filter(user_id=self.request.user.id)
        paginator = Paginator(user_quiz, 9)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        return context


class TeacherAccountViews(LoginRequiredMixin, TemplateView):
    """
    Личный кабинет преподавателя.
    Есть возможность посмотреть все популярные курсы пройденные студентами за определенный период времени
    """
    template_name = 'accounts/teacher.html'


@login_required
def popular_quiz(request):
    """
    Представление для обработки популярных курсов
    """
    context = {}
    if request.method == 'POST':
        date_from = request.POST.get('date_from')
        date_to = request.POST.get('date_to')

        if date_from:
            date_from = make_aware(datetime.strptime(request.POST.get('date_from'), '%Y-%m-%d'))
        else:
            date_from = date.today()
        if date_to:
            date_to = make_aware(datetime.strptime(request.POST.get('date_to'), '%Y-%m-%d'))
        else:
            date_to = date.today()

        quiz_by_date = UniqueValue.objects.filter(create__gte=date_from, create__lte=date_to).values_list('quiz', flat=True)
        quiz_list = list(set(quiz_by_date))
        quiz_count = {i: list(quiz_by_date).count(i) for i in quiz_list}

        quiz = Quiz.objects.filter(id__in=quiz_list)

        data = []
        for quiz_item in quiz_list:
            obj = quiz.get(id=quiz_item)
            data.append(
                {
                    'quiz': obj,
                    'count_quiz': quiz_count.get(quiz_item)
                }
            )

        context['page_obj'] = data
        context['date_from'] = datetime.strftime(date_from, '%d.%m.%Y')
        context['date_to'] = datetime.strftime(date_to, '%d.%m.%Y')

        return render(request, 'accounts/reports/result_popular.html', context)

    return render(request, 'accounts/reports/popular_quiz.html', context)

accounts/templates/accounts/auth_student.html
{% extends 'layouts/base.html' %}

{#{% block content %}#}
{#    <h1>Authorization student</h1>#}
{##}
{#    <form action="." method="post">#}
{#        {% csrf_token %}#}
{#        {{ student_form }}#}
{#        <button type="submit">Зарегистрироваться</button>#}
{#    </form>#}
{#{% endblock %}#}

{% block content %}
    <div class="container">
    <div class="content">

      <main>
        <div class="wrapper">

          <section class="auth">
              <div class="auth__content">
                  <div class="header-block">
                    <h3>Авторизация</h3>
                  </div>

                  <div class="auth__tabs">
                    <a href="{% url 'account:student_auth' %}" class="auth__tabs--item active">Студент</a>
                    <a href="{% url 'account:professor_auth' %}" class="auth__tabs--item">Преподаватель</a>
                  </div>

                  <form action="." class="auth__form" method="post">
                      {% csrf_token %}
                      <label class="field">
                          {{ student_form.username }}
                          {{ student_form.errors.username }}
                         <span class="field__title">
                           Пользователь
                         </span>
                      </label>
                      <label class="field">
                          {{ student_form.first_name }}
                          {{ student_form.errors.first_name }}
                         <span class="field__title">
                           Имя
                         </span>
                      </label>
                      <label class="field">
                          {{ student_form.last_name }}
                          {{ student_form.errors.last_name }}
                         <span class="field__title">
                           Фамилия
                         </span>
                      </label>

                      <label class="field">
                           {{ student_form.study_group }}
                          {{ student_form.errors.study_group }}
                         <span class="field__title">
                          Группа
                         </span>
                       </label>

                       <label class="field">
                           {{ student_form.password1 }}
                           {{ student_form.errors.password1 }}
                         <span class="field__title">
                          Пароль
                         </span>
                       </label>
                      <label class="field">
                           {{ student_form.password2 }}
                          {{ student_form.errors.password2 }}
                         <span class="field__title">
                          Подтвержение пароля
                         </span>
                       </label>

                       <button class="btn btn--primary field__btn" type="submit">Войти</button>
                  </form>
              </div>
          </section>
        </div>
      </main>
    </div>

  </div>
{% endblock %}

accounts/templates/accounts/auth_teacher.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
    <div class="content">

      <main>
        <div class="wrapper">

          <section class="auth">
              <div class="auth__content">
                  <div class="header-block">
                    <h3>Авторизация</h3>
                  </div>

                  <div class="auth__tabs">
                    <a href="{% url 'account:student_auth' %}" class="auth__tabs--item ">Студент</a>
                    <a href="{% url 'account:professor_auth' %}" class="auth__tabs--item active">Преподаватель</a>
                  </div>

                  <form action="." class="auth__form" method="post">
                      {% csrf_token %}
                      <label class="field">
                          {{ form.username }}
                          {{ form.errors.username }}
                         <span class="field__title">
                           Пользователь
                         </span>
                      </label>
                      <label class="field">
                          {{ form.first_name }}
                          {{ form.errors.first_name }}
                         <span class="field__title">
                           Имя
                         </span>
                      </label>
                      <label class="field">
                          {{ form.last_name }}
                          {{ form.errors.last_name }}
                         <span class="field__title">
                           Фамилия
                         </span>
                      </label>
                       <label class="field">
                           {{ form.password1 }}
                           {{ form.errors.password1 }}
                         <span class="field__title">
                          Пароль
                         </span>
                       </label>
                      <label class="field">
                           {{ form.password2 }}
                          {{ form.errors.password2 }}
                         <span class="field__title">
                          Подтвержение пароля
                         </span>
                       </label>

                       <button class="btn btn--primary field__btn" type="submit">Войти</button>
                  </form>
              </div>
          </section>
        </div>
      </main>
    </div>

  </div>
{% endblock %}

accounts/templates/accounts/student.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="content">
            <main>
                <div class="wrapper">
                    <section class="tests__list">
                        <div class="header-block">
                            <h2>
                                Список выполненых тестов
                            </h2>
                        </div>

                        <div class="tests__list--content">
                            {% if page_obj %}
                                {% for result_quiz in page_obj %}
                                    <div class="tests__card">

                                        <h4 class="tests__card--title">{{ result_quiz.quiz.title }}</h4>
                                        <div class="tests__card--desc desc">
                                            <p class="desc__text">
                                                {{ result_quiz.quiz.description }}
                                            </p>

                                            <div class="desc__bottom">
                                                <a href="{% url 'user_tests:result_detail' result_quiz.unique_value %}" class="desc__link"><span
                                                        class="text">Посмотреть результаты</span><span
                                                        class="material-icons">arrow_right_alt</span></a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>

                    </section>
                    {% include 'include/pagination.html' %}
                </div>
            </main>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/teacher.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="content">
            <main>
                <h1>Полулярные курсы</h1>
                <div class="wrapper">
                    <div class="desc__controls">
                        <a href="{% url 'accounts:popular' %}" class="btn btn--primary start">Показать</a>
                    </div>
                </div>

            </main>
        </div>
    </div>
{% endblock %}